### ISSUE TITLE
Forgot to add a file to the repository

### ISSUE THREAD

**Issue by bastetfurry** [alxlab-zone66x/Mac_DB15_to_VGA#1]
Opening the project and trying to change the, at least in Germany, unobtainable VGA socket i got

`Footprint library path "/home/bastetfurry/Projekte/Mac_DB15_to_VGA/kicad/snapeda.pretty" does not exist`

**Comment by alxlab-zone66x** [comment]
Actually it was an unused library. I just removed it and updated all the projects to Kicad 6 format.
